<?php
include('../Connection/Connection.php');
error_reporting(0); //comment this to see warnings and notice

if(isset($_POST['sub']))  
{   

		$Nature=$_POST['Nature'];
		$a=implode(',',$Nature);
		$Purpose=$_POST['Purpose'];
		$b=implode(',',$Purpose);
		$Facility=$_POST['Facility'];
		$c=implode(' ',$Facility);
		$resDate=$_POST['resDate'];
		$TimeStart=$_POST['TimeStart'];
		$TimeEnd=$_POST['TimeEnd'];
		$ReqName=$_POST['ReqName'];
		$School=$_POST['School'];
		$Email=$_POST['Email'];

		$chk= "SELECT * FROM reservationfacility Where `resDate` = '$resDate' AND `Status` = 'Reserved'";
		$dchk = mysqli_query($con, $chk);
		$user = mysqli_fetch_assoc($dchk);
		$sample=$user['Facility'];
		$st=str_split($sample,9);

		//echo $user['Res_id'];
		//echo $c;
		if($user['resDate'] == '$resDate'){
			echo "The Date has conflict";
		}

//LAST EDIT MO DITO PRE

		else if($user['Time_Start'] === $TimeStart && $user['Time_End'] === $TimeEnd && $Facility[0] + " " == $st[0] || $user['Time_Start'] === $TimeStart && $user['Time_End'] === $TimeEnd && $Facility[1] + " " == $st[1] || $user['Time_Start'] === $TimeStart && $user['Time_End'] === $TimeEnd && $Facility[2] + " " == $st[2] || $user['Time_Start'] === $TimeStart && $user['Time_End'] === $TimeEnd && $Facility[3] + " " == $st[3] || $user['Time_Start'] === $TimeStart && $user['Time_End'] === $TimeEnd && $Facility[4] + " " == $st[4] || $user['Time_Start'] === $TimeStart && $user['Time_End'] === $TimeEnd && $Facility[5] + " " == $st[5] || $user['Time_Start'] === $TimeStart && $user['Time_End'] === $TimeEnd && $Facility[6] + " " == $st[6] || $user['Time_Start'] === $TimeStart && $user['Time_End'] === $TimeEnd && $Facility[7] + " " == $st[7] || $user['Time_Start'] === $TimeStart && $user['Time_End'] === $TimeEnd && $Facility[8] + " " == $st[8] || $user['Time_Start'] === $TimeStart && $user['Time_End'] === $TimeEnd && $Facility[9] + " " == $st[9] || $user['Time_Start'] === $TimeStart && $user['Time_End'] === $TimeEnd && $Facility[10] + " " == $st[10] || $user['Time_Start'] === $TimeStart && $user['Time_End'] === $TimeEnd && $Facility[11] + " " == $st[11] || $user['Time_Start'] === $TimeStart && $user['Time_End'] === $TimeEnd && $Facility[12] + " " == $st[12] || $user['Time_Start'] === $TimeStart && $user['Time_End'] === $TimeEnd && $Facility[13] + " " == $st[13] || $user['Time_Start'] === $TimeStart && $user['Time_End'] === $TimeEnd && $Facility[14] + " " == $st[14] || $user['Time_Start'] === $TimeStart && $user['Time_End'] === $TimeEnd && $Facility[15] + " " == $st[15] || $user['Time_Start'] === $TimeStart && $user['Time_End'] === $TimeEnd && $Facility[16] + " " == $st[16] || $user['Time_Start'] === $TimeStart && $user['Time_End'] === $TimeEnd && $Facility[17] + " " == $st[17] || $user['Time_Start'] === $TimeStart && $user['Time_End'] === $TimeEnd && $Facility[18] + " " == $st[18]){
			echo "<h5 style='color:white; background-color:red; padding:10px; margin-bottom:0:'>There is a conflict in schedule with the Facility you are reserving</h5>";
		}

		else if($user['Time_Start'] < $TimeStart && $user['Time_End'] > $TimeEnd && $Facility[0] + " " == $st[0] || $user['Time_Start'] < $TimeStart && $user['Time_End'] > $TimeEnd && $Facility[1] + " " == $st[1] || $user['Time_Start'] < $TimeStart && $user['Time_End'] > $TimeEnd && $Facility[2] + " " == $st[2] || $user['Time_Start'] < $TimeStart && $user['Time_End'] > $TimeEnd && $Facility[3] + " " == $st[3] || $user['Time_Start'] < $TimeStart && $user['Time_End'] > $TimeEnd && $Facility[4] + " " == $st[4] || $user['Time_Start'] < $TimeStart && $user['Time_End'] > $TimeEnd && $Facility[5] + " " == $st[5] || $user['Time_Start'] < $TimeStart && $user['Time_End'] > $TimeEnd && $Facility[6] + " " == $st[6] || $user['Time_Start'] < $TimeStart && $user['Time_End'] > $TimeEnd && $Facility[7] + " " == $st[7] || $user['Time_Start'] < $TimeStart && $user['Time_End'] > $TimeEnd && $Facility[8] + " " == $st[8] || $user['Time_Start'] < $TimeStart && $user['Time_End'] > $TimeEnd && $Facility[9] + " " == $st[9] || $user['Time_Start'] < $TimeStart && $user['Time_End'] > $TimeEnd && $Facility[10] + " " == $st[10] || $user['Time_Start'] < $TimeStart && $user['Time_End'] > $TimeEnd && $Facility[11] + " " == $st[11] || $user['Time_Start'] < $TimeStart && $user['Time_End'] > $TimeEnd && $Facility[12] + " " == $st[12] || $user['Time_Start'] < $TimeStart && $user['Time_End'] > $TimeEnd && $Facility[13] + " " == $st[13] || $user['Time_Start'] < $TimeStart && $user['Time_End'] > $TimeEnd && $Facility[14] + " " == $st[14] || $user['Time_Start'] < $TimeStart && $user['Time_End'] > $TimeEnd && $Facility[15] + " " == $st[15] || $user['Time_Start'] < $TimeStart && $user['Time_End'] > $TimeEnd && $Facility[16] + " " == $st[16] || $user['Time_Start'] < $TimeStart && $user['Time_End'] > $TimeEnd && $Facility[17] + " " == $st[17] || $user['Time_Start'] < $TimeStart && $user['Time_End'] > $TimeEnd && $Facility[18] + " " == $st[18]){
			echo "<h5 style='color:white; background-color:red; padding:10px; margin-bottom:0:'>There is a conflict in schedule with the Facility you are reserving</h5>";
		}

		else if($user['Time_Start'] > $TimeStart && $user['Time_End'] < $TimeEnd && $Facility[0] + " " == $st[0] || $user['Time_Start'] > $TimeStart && $user['Time_End'] < $TimeEnd && $Facility[1] + " " == $st[1] || $user['Time_Start'] > $TimeStart && $user['Time_End'] < $TimeEnd && $Facility[2] + " " == $st[2] || $user['Time_Start'] > $TimeStart && $user['Time_End'] < $TimeEnd && $Facility[3] + " " == $st[3] || $user['Time_Start'] > $TimeStart && $user['Time_End'] < $TimeEnd && $Facility[4] + " " == $st[4] || $user['Time_Start'] > $TimeStart && $user['Time_End'] < $TimeEnd && $Facility[5] + " " == $st[5] || $user['Time_Start'] > $TimeStart && $user['Time_End'] < $TimeEnd && $Facility[6] + " " == $st[6] || $user['Time_Start'] > $TimeStart && $user['Time_End'] < $TimeEnd && $Facility[7] + " " == $st[7] || $user['Time_Start'] > $TimeStart && $user['Time_End'] < $TimeEnd && $Facility[8] + " " == $st[8] || $user['Time_Start'] > $TimeStart && $user['Time_End'] < $TimeEnd && $Facility[9] + " " == $st[9] || $user['Time_Start'] > $TimeStart && $user['Time_End'] < $TimeEnd && $Facility[10] + " " == $st[10] || $user['Time_Start'] > $TimeStart && $user['Time_End'] < $TimeEnd && $Facility[11] + " " == $st[11] || $user['Time_Start'] > $TimeStart && $user['Time_End'] < $TimeEnd && $Facility[12] + " " == $st[12] || $user['Time_Start'] > $TimeStart && $user['Time_End'] < $TimeEnd && $Facility[13] + " " == $st[13] || $user['Time_Start'] > $TimeStart && $user['Time_End'] < $TimeEnd && $Facility[14] + " " == $st[14] || $user['Time_Start'] > $TimeStart && $user['Time_End'] < $TimeEnd && $Facility[15] + " " == $st[15] || $user['Time_Start'] > $TimeStart && $user['Time_End'] < $TimeEnd && $Facility[16] + " " == $st[16] || $user['Time_Start'] > $TimeStart && $user['Time_End'] < $TimeEnd && $Facility[17] + " " == $st[17] || $user['Time_Start'] > $TimeStart && $user['Time_End'] < $TimeEnd && $Facility[18] + " " == $st[18]){
			echo "<h5 style='color:white; background-color:red; padding:10px; margin-bottom:0:'>There is a conflict in schedule with the Facility you are reserving</h5>";
		}

		else if($user['Time_Start'] > $TimeStart && $user['Time_Start'] < $TimeEnd && $Facility[0] + " " == $st[0] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] < $TimeEnd && $Facility[1] + " " == $st[1] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] < $TimeEnd && $Facility[2] + " " == $st[2] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] < $TimeEnd && $Facility[3] + " " == $st[3] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] < $TimeEnd && $Facility[4] + " " == $st[4] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] < $TimeEnd && $Facility[5] + " " == $st[5] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] < $TimeEnd && $Facility[6] + " " == $st[6] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] < $TimeEnd && $Facility[7] + " " == $st[7] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] < $TimeEnd && $Facility[8] + " " == $st[8] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] < $TimeEnd && $Facility[9] + " " == $st[9] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] < $TimeEnd && $Facility[10] + " " == $st[10] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] < $TimeEnd && $Facility[11] + " " == $st[11] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] < $TimeEnd && $Facility[12] + " " == $st[12] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] < $TimeEnd && $Facility[13] + " " == $st[13] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] < $TimeEnd && $Facility[14] + " " == $st[14] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] < $TimeEnd && $Facility[15] + " " == $st[15] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] < $TimeEnd && $Facility[16] + " " == $st[16] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] < $TimeEnd && $Facility[17] + " " == $st[17] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] < $TimeEnd && $Facility[18] + " " == $st[18]){
			echo "<h5 style='color:white; background-color:red; padding:10px; margin-bottom:0:'>There is a conflict in schedule with the Facility you are reserving</h5>";
		}

		else if($user['Time_Start'] > $TimeStart && $user['Time_Start'] <= $TimeEnd && $Facility[0] + " " == $st[0] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] <= $TimeEnd && $Facility[1] + " " == $st[1] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] <= $TimeEnd && $Facility[2] + " " == $st[2] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] <= $TimeEnd && $Facility[3] + " " == $st[3] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] <= $TimeEnd && $Facility[4] + " " == $st[4] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] <= $TimeEnd && $Facility[5] + " " == $st[5] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] <= $TimeEnd && $Facility[6] + " " == $st[6] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] <= $TimeEnd && $Facility[7] + " " == $st[7] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] <= $TimeEnd && $Facility[8] + " " == $st[8] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] <= $TimeEnd && $Facility[9] + " " == $st[9] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] <= $TimeEnd && $Facility[10] + " " == $st[10] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] <= $TimeEnd && $Facility[11] + " " == $st[11] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] <= $TimeEnd && $Facility[12] + " " == $st[12] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] <= $TimeEnd && $Facility[13] + " " == $st[13] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] <= $TimeEnd && $Facility[14] + " " == $st[14] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] <= $TimeEnd && $Facility[15] + " " == $st[15] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] <= $TimeEnd && $Facility[16] + " " == $st[16] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] <= $TimeEnd && $Facility[17] + " " == $st[17] || $user['Time_Start'] > $TimeStart && $user['Time_Start'] <= $TimeEnd && $Facility[18] + " " == $st[18]){
			echo "<h5 style='color:white; background-color:red; padding:10px; margin-bottom:0:'>There is a conflict in schedule with the Facility you are reserving</h5>";
		}

		else if($user['Time_End'] > $TimeStart && $user['Time_End'] <= $TimeEnd && $Facility[0] + " " == $st[0] || $user['Time_End'] > $TimeStart && $user['Time_End'] <= $TimeEnd && $Facility[1] + " " == $st[1] || $user['Time_End'] > $TimeStart && $user['Time_End'] <= $TimeEnd && $Facility[2] + " " == $st[2] || $user['Time_End'] > $TimeStart && $user['Time_End'] <= $TimeEnd && $Facility[3] + " " == $st[3] || $user['Time_End'] > $TimeStart && $user['Time_End'] <= $TimeEnd && $Facility[4] + " " == $st[4] || $user['Time_End'] > $TimeStart && $user['Time_End'] <= $TimeEnd && $Facility[5] + " " == $st[5] || $user['Time_End'] > $TimeStart && $user['Time_End'] <= $TimeEnd && $Facility[6] + " " == $st[6] || $user['Time_End'] > $TimeStart && $user['Time_End'] <= $TimeEnd && $Facility[7] + " " == $st[7] || $user['Time_End'] > $TimeStart && $user['Time_End'] <= $TimeEnd && $Facility[8] + " " == $st[8] || $user['Time_End'] > $TimeStart && $user['Time_End'] <= $TimeEnd && $Facility[9] + " " == $st[9] || $user['Time_End'] > $TimeStart && $user['Time_End'] <= $TimeEnd && $Facility[10] + " " == $st[10] || $user['Time_End'] > $TimeStart && $user['Time_End'] <= $TimeEnd && $Facility[11] + " " == $st[11] || $user['Time_End'] > $TimeStart && $user['Time_End'] <= $TimeEnd && $Facility[12] + " " == $st[12] || $user['Time_End'] > $TimeStart && $user['Time_End'] <= $TimeEnd && $Facility[13] + " " == $st[13] || $user['Time_End'] > $TimeStart && $user['Time_End'] <= $TimeEnd && $Facility[14] + " " == $st[14] || $user['Time_End'] > $TimeStart && $user['Time_End'] <= $TimeEnd && $Facility[15] + " " == $st[15] || $user['Time_End'] > $TimeStart && $user['Time_End'] <= $TimeEnd && $Facility[16] + " " == $st[16] || $user['Time_End'] > $TimeStart && $user['Time_End'] <= $TimeEnd && $Facility[17] + " " == $st[17] || $user['Time_End'] > $TimeStart && $user['Time_End'] <= $TimeEnd && $Facility[18] + " " == $st[18]){
			echo "<h5 style='color:white; background-color:red; padding:10px; margin-bottom:0:'>There is a conflict in schedule with the Facility you are reserving</h5>";
		}

		else{
			$qry="INSERT INTO reservationfacility(`nature`,`Purpose`,`Facility`,`resDate`,`Time_Start`,`Time_End`,`ReqName`,`School`,`Email`) VALUES('$a','$b','$c','$resDate','$TimeStart','$TimeEnd','$ReqName','$School','$Email')";
			mysqli_query($con,$qry);
			header('location: Facility_Res_Confirmation.php');
			//echo"booked";
		}
}

?>
